### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by dell-mic** [binarykitchen/find-remove#28]
Hi,

thanks a lot for this package. 

While upgrading some projects to node 16 (will be the next LTS version) I noticed that this package claims to not be compatible:
`error find-remove@3.0.1: The engine "node" is incompatible with this module. Expected version "^14.4.0". Got "16.0.0"
error Found incompatible module.`

I have not yet tested if everything would still run when installed with `--ignore-engines`. The installation itself went fine, however.

Best,
Michael

**Comment by binarykitchen** [comment]
You are fast mate, being already on node v16.0.0 (while it doesn't attract me yet)

Alright, I've run some tests myself, improved coverage and since there are no breaking changes, only made a minor version bump: v3.1.0 is out to embrace node v15 + v16 both.

Thanks for pushing. Hope all is swell now. Cheers :)

**Comment by dell-mic** [comment]
And you have been quite fast addressing this! Thank you very much!

Looks like everything ist still working fine with node 16 for me as well.
